App_blog/urls.py
from django.urls import path
from .views import posts, post_detail, formulario, publicar, about

app_name = 'App_blog'

urlpatterns = [
    path('', posts, name="posts"),
    path('<int:post_id>', post_detail, name="post_detail"),
    path('formulario/', formulario, name="formulario"),
    path('publicar/', publicar, name="publicar"),
    path('about/', about, name="about"),
]

blog_personal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings # importar STATIC_URL = 'static/'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_blog.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_blog/models.py
from datetime import datetime
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=70)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

App_blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Post

def posts(request):
    posts = Post.objects.all()[::-1]
    return render(request, 'posts.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {'post': post})

def formulario(request):
    return render(request, 'formulario.html')

def publicar(request):
    if request.method == "POST":
        titulo = request.POST['txtTitulo']
        descripcion = request.POST['txtDescripcion']
        imagen = request.FILES['imagen']
        fecha = request.POST['txtFecha']
        publicacion = Post.objects.create(title=titulo,description=descripcion,image=imagen,date=fecha)
        return redirect('/')

def about(request):
    return render(request, 'about.html')

App_blog/templates/_partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-gradient">
    <div class="container-fluid">
        {% comment %} <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
            <button class="btn btn-outline-light" type="submit">Buscar</button>
        </form> {% endcomment %}
        <p class="h5 text-secondary">Mi Blog</p>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'App_blog:posts' %}">Publicaciones</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'App_blog:formulario' %}">Publicar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'App_blog:about' %}">Información</a>
                </li>
            </ul>
        </div>
    </div>
  </nav>

App_blog/templates/about.html
{% extends 'layout.html' %}
<head>
    {% load static %}
    <title>{% block title %}Información{% endblock title %}</title>
</head>
<body>
    {% block body %}
    <div class="container-fluid">
        <div class="p-5">
            <div class="card card-body bg-black bg-gradient text-light">
                <div class="row">
                    <div class="col-3">
                        <img src="{% static '20210530_111222.jpg' %}" alt="foto" class="img-fluid rounded-circle mt-2">
                    </div>
                    <div class="col-9 my-auto text-center">
                        <h2>Jean Pool Oliver Yantas Inocente</h2>
                        <p>Eres tan grande como te propongas serlo, y puedes llegar tan lejos como te dé la gana, ánimo.😎🏃‍♂️</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock body %}
</body>

App_blog/templates/formulario.html
{% extends 'layout.html' %}
<head>
    <title>{% block title %}Formulario{% endblock title %}</title>
</head>
{% block body %}
<body>
    <div class="mx-5 my-3">
        <form action="/publicar/" method="POST" enctype="multipart/form-data" class="form-control bg-black bg-gradient text-light">{% csrf_token %}
            <div class="mb-3">
                <label for="txtTitulo" class="form-label">Título</label>
                <input type="text" name="txtTitulo" class="form-control bg-black bg-gradient text-light" required>
            </div>
            <div class="mb-3">
                <label for="txtDescripcion" class="form-label">Descripción</label>
                <textarea name="txtDescripcion" rows="6" style="resize: none;" class="form-control bg-black bg-gradient text-light" required></textarea>
            </div>
            <div class="mb-3">
                <label for="imagen" class="form-label">Imagen</label>
                <input type="file" name="imagen" class="form-control bg-black bg-gradient text-light" required>
            </div>
            <div class="mb-3">
                <label for="txtFecha" class="form-label">Fecha</label>
                <input type="date" name="txtFecha" class="form-control bg-black bg-gradient text-light" required>
            </div>
            <div class="mb-3">
                <input type="submit" class="form-control btn btn-primary" value="Publicar">
            </div>
        </form>
    </div>
</body>
{% endblock body %}

App_blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body class="bg-secondary">
    {% include '_partials/_navbar.html' %}
    {% block body %}{% endblock body %}
    <script src="{% static 'bootstrap/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

App_blog/templates/post_detail.html
{% extends 'layout.html' %}
<head>
    <title>{% block title %} {{ post.title }} {% endblock title %}</title>
</head>

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-11">
            <div class="text-center mt-2">
                <h2>{{ post.title }}</h2>
                <h3 class="my-2 h5 text-muted">{{ post.date|date:'F jS Y' }}</h3>
            
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid rounded-3 img-post-detail">
            
                <div class="my-4 lh-1 justificado">
                    <p>{{ post.description }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-1">
            <div class="d-flex justify-content-end m-3">
                <a href="{% url 'App_blog:posts' %}" class="btn btn-dark">Atrás</a>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

App_blog/templates/posts.html
{% extends 'layout.html' %}

<head>
    <title>{% block title %}Inicio{% endblock title %}</title>
</head>
<body>
    {% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <p class="p-3 h4">
                    Publicaciones
                </p>
                {% for post in posts %}
                <div class="p-3">
                    <div class="card card-body bg-black bg-gradient text-light">
                        <div class="row">
                            <div class="col-3">
                                <img src="{{ post.image.url }}" alt="{{post.title}}" class="img-fluid rounded-3 mt-2">
                            </div>
                            <div class="col-9">
                                <h2>{{ post.title }}</h2>
                                <p>{{ post.description|truncatechars:100 }}</p>
                                <p>{{ post.date|date:'M d Y'|upper }}</p>

                                <a href="{% url 'App_blog:post_detail' post.id %}" class="btn btn-primary">Leer más</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col-md-4">
                <div class="p-3 h4">
                    Índice
                    <div class="mt-5 list-group">
                        {% for post in posts %}
                        <a href="{% url 'App_blog:post_detail' post.id %}" class="h6 list-group-item list-group-item-action"><li class="indice-li">{{ post.title }}</li></a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock body %}
</body>